name: roggle
description: Simple, colorful and easy to expand logger for dart.
version: 0.1.0
homepage: https://github.com/susatthi/roggle

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  logger: ^1.1.0
  meta: ^1.7.0
  stack_trace: ^1.10.0

dev_dependencies:
  pedantic_mono: ^1.18.0
  test: ^1.21.1

