name: Dartdoc

on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - main

jobs:
  dartdoc:
    name: Dartdoc
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: google/dart:2.14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run Dartdoc
        run: |
          dart pub global activate dartdoc
          dartdoc
      - name: Deploy API doc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/api
