name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: google/dart:2.14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: dart pub get
      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Static analyze project
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Run tests
        run: dart test --coverage=coverage
      - name: Convert coverage to ICOV
        run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage/lcov.info
          fail_ci_if_error: true
          flags: unittests
          verbose: true
